#!/bin/bash
#
#   aliasrc
#

alias nano="$EDITOR"
alias vim="nvim"
alias config="/usr/bin/git --git-dir=/home/pinkieboi/.dotfiles/ --work-tree=/home/pinkieboi"

### Filesystem
    # ls
alias ls="colorls --dark"
alias la="colorls --dark -ah"
alias ll="colorls --dark -lah"
alias lm="colorls --dark -m"
alias lr="colorls --dark -R"
alias l.="colorls --dark -Ah | egrep '^\.'"
alias lg="colorls --dark -l --group-directories-first"
    # grep
alias grep="grep --color=always"
alias egrep="egrep --color=always"
alias fgrep="fgrep --color=always"
    # ripgrep
alias rg="rg --sort path"
    # git
alias gcl='git clone --depth 1'
alias gi='git init'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push origin master'
alias config='/usr/bin/git --git-dir=/home/pinkieboi/.dotfiles/ --work-tree=/home/pinkieboi'

### System info
alias df='df -h'
alias probe="sudo -E hw-probe -all -upload"
alias free="free -mt"
alias hw="hwinfo --short"
    # Userlist
alias userlist="cut -d: -f1 /etc/passwd"
    # Merge new settings
alias merge="xrdb -merge ~/.Xresources"
    # Journalctl error messages
alias jctl="journalctl -p 3 -xb"
    # Add new fonts
alias update-fc='sudo fc-cache -fv'
    # Current Processes
alias psa="ps auxf"
alias psgrep="ps aux | grep -v grep | grep -i -e VSZ -e"
    # Check vulnerabilities microcode
alias microcode='grep . /sys/devices/system/cpu/vulnerabilities/*'
    # Use all cores
alias uac="sh ~/.bin/main/000*"
    # Maintenance
alias big="expac -H M '%m\t%n' | sort -h | nl"
    # List installed desktops
alias xd="ls /usr/share/xsessions"

### Edit important configration files
alias zshrc="$EDITOR ~/.zshrc"
alias bashrc="$EDITOR ~/.bashrc"
alias vimrc="$EDITOR ~/.vimrc"
alias aliasrc="$EDITOR ~/.config/shell/aliasrc"
alias efstab="sudo $EDITOR /etc/fstab"
alias ensswitch="sudo $EDITOR /etc/nsswitch.conf"
alias esamba="sudo $EDITOR /etc/samba/smb.conf"
alias emkinitcpio="sudo $EDITOR /etc/mkinitcpio.conf"
alias eslim="sudo $EDITOR /etc/slim.conf"
alias eoblogout="sudo $EDITOR /etc/oblogout.conf"
alias epacman="sudo $EDITOR /etc/pacman.conf"
alias epkbuild="$EDITOR -w PKGBUILD"
    # Display Manager
alias esddm="sudo $EDITOR /etc/sddm.conf"
alias elightdm="sudo $EDITOR /etc/lightdm/lightdm.conf"
    # Grub
alias egrub="sudo $EDITOR /etc/default/grub"
alias econfgrub="sudo $EDITOR /boot/grub/grub.cfg"
    # Update Grub
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"

    # Switch default shell
alias tobash="sudo chsh $USER -s /bin/bash && echo 'Now log out.'"
alias tozsh="sudo chsh $USER -s /bin/zsh && echo 'Now log out.'"
    # Switch to lightdm display manager
alias tolightdm="sudo pacman -S lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings --noconfirm --needed ; sudo systemctl enable lightdm.service -f ; echo 'Lightm is active - reboot now'"
    # Switch to SDDM display manager
alias tosddm="sudo pacman -S sddm --noconfirm --needed ; sudo systemctl enable sddm.service -f ; echo 'Sddm is active - reboot now'"

# Package managment
    # pacman/paru/yay
alias pacman='sudo pacman --color auto'
alias paru="paru --bottomup"
alias update='sudo pacman -Syyu'
alias upall="yay -Syyu --noconfirm"
    # pacman unlock
alias unlock="sudo rm /var/lib/pacman/db.lck"
    # Recent Installed Packages
alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -200 | nl"
alias riplong="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -3000 | nl"
    # maintenance
alias big="expac -H M '%m\t%n' | sort -h | nl"
    # Cleanup orphaned packages
alias cleanup='sudo pacman -Rns $(pacman -Qtdq)'
    # Edit Mirror List
alias emirrorlist="sudo $EDITOR /etc/pacman.d/mirrorlist"
    # Update Mirrors
alias mirror="sudo reflector --latest 50 --protocol http,https --sort rate --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector -f 30 -l 30 --number 20 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrorb="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

## Downloads
    # Wget continue download
alias wget="wget -c"
    # youtube-dl
alias yta="youtube-dl --extract-audio --audio-format best "
alias ytv="youtube-dl -f bestvideo+bestaudio "

# Color man pages
export LESS_TERMCAP_mb=$'\E[01;32m'
export LESS_TERMCAP_md=$'\E[01;32m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;47;34m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;36m'
export LESS=-r

# # ex = EXtractor for all kinds of archives
# # usage: ex <file>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.tar.xz)    tar xf $1    ;;
      *.tar.zst)   tar xf $1    ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

#copy/paste all content of /etc/skel over to home folder - backup of config created - beware
alias skel='cp -Rf ~/.config ~/.config-backup-$(date +%Y.%m.%d-%H.%M.%S) && cp -rf /etc/skel/* ~'
#backup contents of /etc/skel to hidden backup folder in home/user
alias bupskel='cp -Rf /etc/skel ~/.skel-backup-$(date +%Y.%m.%d-%H.%M.%S)'

#copy bashrc-latest over on bashrc - cb= copy bashrc
alias cb='sudo cp /etc/skel/.bashrc ~/.bashrc && source ~/.bashrc'
#copy /etc/skel/.zshrc over on ~/.zshrc - cb= copy zshrc
alias cz='sudo cp /etc/skel/.zshrc ~/.zshrc && exec zsh'

#mounting the folder Public for exchange between host and guest on virtualbox
alias vbm="sudo /usr/local/bin/arcolinux-vbox-share"
