#!/usr/bin/env bash
#
#   aliasrc
#

alias config="/usr/bin/git --git-dir=/home/pinkieboi/.dotfiles/ --work-tree=/home/pinkieboi"
alias nano="$EDITOR"
alias more='less'
alias ":q"="exit"
alias hist='history | grep'

# cd
alias home='cd ~'
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# ls
alias ls="lsd -h --group-dirs=first --icon=always"
alias la="lsd -ah --group-dirs=first --icon=always --dereference"
alias ll="lsd -lah --group-dirs=first --icon=always --dereference"
alias lx="lsd -xb --icon=always --dereference"                  # sort by extension
alias lk="lsd -lSr --icon=always --dereference"                 # sort by size, biggest last
alias lc="lsd -ltcr --icon=always --dereference"                # sort by and show change time, most recent last
alias lu="lsd -ltur --icon=always --dereference"                # sort by and show access time, most recent last
alias lt="lsd -ltr --icon=always --dereference"                 # sort by date, most recent last
alias lm="lsd -al --icon=always | more --dereference"           # pipe through 'more'
alias lr="lsd -lR --icon=always --dereference"                  # recursive ls
alias lsr="tree -Csu"                                              # nice alternative to 'recursive ls'

# grep
alias grep="grep --color=always"
alias egrep="egrep --color=always"
alias fgrep="fgrep --color=always"
# ripgrep
alias rg="rg --sort path"
# bat
alias cat="bat --theme=Dracula"

# System
alias df='df -kTh'
alias du="du -kh"
alias free="free -mt"st
alias hw="hwinfo --short"
alias probe="sudo -E hw-probe -all -upload"
alias diskchk="lsblk -d -e 7 -o name,rota,disc-max,model,ptuuid"
alias listusb='lsblk -p -S -o name,tran,rm | grep "usb" | cut -d " " -f1'
alias userlist="cut -d: -f1 /etc/passwd"
    # Merge new settings
alias merge="xrdb -merge ~/.Xresources"
    # Journalctl error messages
alias jctl="journalctl -p 3 -xb"
    # Add new fonts
alias update-fc='sudo fc-cache -fv'
    # Current Processes
alias psa="ps auxf"
alias psgrep="ps aux | grep -v grep | grep -i -e VSZ -e"
    # Check vulnerabilities microcode
alias microcode='grep . /sys/devices/system/cpu/vulnerabilities/*'
    # Maintenance
alias big="expac -H M '%m\t%n' | sort -h | nl"
    # List installed desktops
alias xd="ls /usr/share/xsessions"
    # Update icon cache
alias updateicons="gtk-update-icon-cache -f -t /usr/share/icons/"
## system commands / trouble shooting
alias mkinitp="sudo mkinitcpio -p linux"
alias fixgnupg="chown -R $(whoami) ~/.gnupg/ | find ~/.gnupg -type f -exec chmod 600 {} \; | find ~/.gnupg -type d -exec chmod 700 {} \;"
# smb / nmb services restart
alias rstsmb="sudo systemctl restart smb.service"
alias rstnmb="sudo systemctl restart nmb.service" 


### Edit important configration files
alias zshrc="$EDITOR ~/.zshrc"
alias bashrc="$EDITOR ~/.bashrc"
alias vimrc="$EDITOR ~/.vimrc"
alias nvimrc="$EDITOR ~/.config/nvim/init.lua"
alias aliasrc="$EDITOR ~/.config/aliasrc"
alias efstab="sudo $EDITOR /etc/fstab"
alias ensswitch="sudo $EDITOR /etc/nsswitch.conf"
alias esamba="sudo $EDITOR /etc/samba/smb.conf"
alias emkinitcpio="sudo $EDITOR /etc/mkinitcpio.conf"
alias eslim="sudo $EDITOR /etc/slim.conf"
alias eoblogout="sudo $EDITOR /etc/oblogout.conf"
alias epacman="sudo $EDITOR /etc/pacman.conf"
alias epkbuild="$EDITOR -w PKGBUILD"
    # Display Manager
alias esddm="sudo $EDITOR /etc/sddm.conf"
alias elightdm="sudo $EDITOR /etc/lightdm/lightdm.conf"
    # Grub
alias egrub="sudo $EDITOR /etc/default/grub"
alias econfgrub="sudo $EDITOR /boot/grub/grub.cfg"
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"
    # Switch default shell
alias tobash="sudo chsh $USER -s /bin/bash && echo 'Now log out.'"
alias tozsh="sudo chsh $USER -s /bin/zsh && echo 'Now log out.'"

# Package managment
alias paru="paru --bottomup"
alias upall="yay -Syyu --noconfirm"
alias unlock="sudo rm /var/lib/pacman/db.lck"        # pacman unlock
alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -200 | nl"       # Recent Installed Packages
alias riplong="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -3000 | nl"
alias installed="pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'"            # fzf installed packages split pane view
alias savepkgs="sudo pacman -Qqen > $HOME/pkgs-arch-ABS.txt && sudo pacman -Qqem > $HOME/pkgs-arch-AUR.txt"         # save 2 lists of installed pkgs (arch repos & AUR)
    # maintenance
alias big="expac -H M '%m\t%n' | sort -h | nl"
alias rmcache="paru -Scc && sudo pacman -Scc"                       # Clean package cache
alias cleanup="sudo pacman -Qdtq | sudo pacman -Rns -"              # Clean orphaned pkgs

    # Edit Mirror List
alias emirrorlist="sudo $EDITOR /etc/pacman.d/mirrorlist"
    # Update Mirrors
alias mirror="sudo reflector --latest 50 --protocol http,https --sort rate --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector -f 30 -l 30 --number 20 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrorb="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias reflectuk="sudo reflector --vervose --country 'United Kingdom' --age 6 --protocol https --sort rate --save /etc/pacman.d/mirrorlist"

## Other useful aliases
    # Clean python crud
alias pyclean='find . -name \*.pyc -o -name \*.pyo -o -name __pycache__ -delete'
    # improve png
alias fixpng='find . -type f -name "*.png" -exec convert {} -strip {} \;'

# Reaload bashrc/zshrc
alias rlb='clear && . ~/.bashrc'
alias rlz="clear && . ~/.zshrc"

# Local / Public IP
alias mypip="curl ipecho.net/plain; echo"
alias mylip="ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'"
alias mynet="lspci -knn|grep -iA2 net"
alias mynethw='hwinfo --netcard --wlan --bluetooth | grep -Ei "model\:|driver\:|status\:|cmd\:|file\:|detected\:" | grep -v "Config Status"'


#mounting the folder Public for exchange between host and guest on virtualbox
alias vboxmount="mount -t vboxsf -o rw,uid=$UID,gid=$UID Public /home/$USER/Public"

## Downloads
alias wget="wget -c"                                # Continue
alias yta="yt-dlp -x --audio-format mp3 "           # MP3 audio only
alias ytv="yt-dlp -f bestvideo+bestaudio "          # Best audio/video combination

# the terminal rickroll
alias rr='curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash'

# XMR Miner
alias xmrig="sudo $HOME/.bin/enable_1gb_pages.sh && sudo xmrig -c $HOME/.config/xmrig.json"

## Virus Scanning
alias scanh="clamdscan --multiscan --fdpass $HOME"

## Neovim
alias kvim='NVIM_APPNAME="nvim-kickstart" nvim'
alias vim='nvim'

# Git
alias gc='git clone'
#alias addup='git add -u'
#alias addall='git add .'
#alias branch='git branch'
#alias checkout='git checkout'
#alias commit='git commit -m'
#alias fetch='git fetch'
#alias pull='git pull origin'
#alias push='git push origin'
#alias stat='git status'  # 'status' is protected name so using 'stat' instead
#alias tag='git tag'
#alias newtag='git tag -a'

# Color man pages
# export LESS_TERMCAP_mb=$'\E[01;32m'
# export LESS_TERMCAP_md=$'\E[01;32m'
# export LESS_TERMCAP_me=$'\E[0m'
# export LESS_TERMCAP_se=$'\E[0m'
# export LESS_TERMCAP_so=$'\E[01;47;34m'
# export LESS_TERMCAP_ue=$'\E[0m'
# export LESS_TERMCAP_us=$'\E[01;36m'
# export LESS=-r

# # ex = EXtractor for all kinds of archives
# # usage: ex <file>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.tar.xz)    tar xf $1    ;;
      *.tar.zst)   tar xf $1    ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# syntax:bash
