[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]
live_config_reload = true

[window]
decorations = "None"
opacity = 0.95
blur = true
title = "Alacritty"
dynamic_title = true
padding = { x= 3, y = 5 }
dynamic_padding = true

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "bold" }
italic = { family = "FiraCode Nerd Font", style = "italic" }
size = 11.0

[cursor]
style = { shape = "Block" }
vi_mode_style = { shape = "Beam" }
unfocused_hollow = true

[terminal]
shell = "/bin/zsh"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "F11", mods = "Control", action = "ToggleFullscreen" }
]

